---
deployment:
  tasks:
    - export DEPLOYPATH=/home/studentsw/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - cd /home/studentsw/repositories/StudentsWriting/client
    - /usr/bin/npm install
    - /usr/bin/npm run build
    - /bin/cp -R build/* $DEPLOYPATH
