---
deployment:
  tasks:
    - export DEPLOYPATH=/home/studentsw/public_html
    - cd /home/studentsw/repositories/StudentsWriting/client
    - /home/studentsw/bin/npm install
    - /home/studentsw/bin/npm run build
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R build/* $DEPLOYPATH
