const PARAGRAPHS = [
  {
    id: 1,
    tokens: [
      { word: "The",      isVerb: false },
      { word: "cat",      isVerb: false },
      { word: "jumped",   isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "over",     isVerb: false },
      { word: "the",      isVerb: false },
      { word: "fence",    isVerb: false },
      { word: "and",      isVerb: false },
      { word: "ran",      isVerb: true,  type: "Action",  choices: ["Action", "Helping", "Linking"] },
      { word: "into",     isVerb: false },
      { word: "the",      isVerb: false },
      { word: "garden",   isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 2,
    tokens: [
      { word: "She",      isVerb: false },
      { word: "is",       isVerb: true,  type: "Linking", choices: ["Linking", "Action", "Helping"] },
      { word: "the",      isVerb: false },
      { word: "best",     isVerb: false },
      { word: "student",  isVerb: false },
      { word: "in",       isVerb: false },
      { word: "class",    isVerb: false },
      { word: ".",        isVerb: false },
      { word: "She",      isVerb: false },
      { word: "has",      isVerb: true,  type: "Helping", choices: ["Helping", "Action", "Linking"] },
      { word: "studied",  isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "hard",     isVerb: false },
      { word: "all",      isVerb: false },
      { word: "year",     isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 3,
    tokens: [
      { word: "The",      isVerb: false },
      { word: "dog",      isVerb: false },
      { word: "was",      isVerb: true,  type: "Helping", choices: ["Helping", "Linking", "Action"] },
      { word: "barking",  isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "loudly",   isVerb: false },
      { word: "at",       isVerb: false },
      { word: "the",      isVerb: false },
      { word: "door",     isVerb: false },
      { word: ".",        isVerb: false },
      { word: "It",       isVerb: false },
      { word: "seemed",   isVerb: true,  type: "Linking", choices: ["Linking", "Action", "Helping"] },
      { word: "scared",   isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 4,
    tokens: [
      { word: "We",       isVerb: false },
      { word: "should",   isVerb: true,  type: "Helping", choices: ["Helping", "Action", "Linking"] },
      { word: "finish",   isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "our",      isVerb: false },
      { word: "project",  isVerb: false },
      { word: "before",   isVerb: false },
      { word: "Friday",   isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 5,
    tokens: [
      { word: "The",      isVerb: false },
      { word: "flowers",  isVerb: false },
      { word: "smell",    isVerb: true,  type: "Linking", choices: ["Linking", "Action", "Helping"] },
      { word: "wonderful" ,isVerb: false },
      { word: "in",       isVerb: false },
      { word: "spring",   isVerb: false },
      { word: ".",        isVerb: false },
      { word: "The",      isVerb: false },
      { word: "bees",     isVerb: false },
      { word: "buzz",     isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "around",   isVerb: false },
      { word: "them",     isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 6,
    tokens: [
      { word: "Jake",     isVerb: false },
      { word: "can",      isVerb: true,  type: "Helping", choices: ["Helping", "Action", "Linking"] },
      { word: "play",     isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "the",      isVerb: false },
      { word: "guitar",   isVerb: false },
      { word: "and",      isVerb: false },
      { word: "sing",     isVerb: true,  type: "Action",  choices: ["Action", "Helping", "Linking"] },
      { word: "at",       isVerb: false },
      { word: "the",      isVerb: false },
      { word: "same",     isVerb: false },
      { word: "time",     isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 7,
    tokens: [
      { word: "My",       isVerb: false },
      { word: "mom",      isVerb: false },
      { word: "baked",    isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "cookies",  isVerb: false },
      { word: "and",      isVerb: false },
      { word: "they",     isVerb: false },
      { word: "taste",    isVerb: true,  type: "Linking", choices: ["Linking", "Action", "Helping"] },
      { word: "amazing",  isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 8,
    tokens: [
      { word: "The",      isVerb: false },
      { word: "students", isVerb: false },
      { word: "were",     isVerb: true,  type: "Helping", choices: ["Helping", "Linking", "Action"] },
      { word: "studying", isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "for",      isVerb: false },
      { word: "the",      isVerb: false },
      { word: "big",      isVerb: false },
      { word: "test",     isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 9,
    tokens: [
      { word: "The",      isVerb: false },
      { word: "sky",      isVerb: false },
      { word: "looks",    isVerb: true,  type: "Linking", choices: ["Linking", "Action", "Helping"] },
      { word: "very",     isVerb: false },
      { word: "dark",     isVerb: false },
      { word: ".",        isVerb: false },
      { word: "It",       isVerb: false },
      { word: "might",    isVerb: true,  type: "Helping", choices: ["Helping", "Action", "Linking"] },
      { word: "rain",     isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "soon",     isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
  {
    id: 10,
    tokens: [
      { word: "Emma",     isVerb: false },
      { word: "wrote",    isVerb: true,  type: "Action",  choices: ["Action", "Linking", "Helping"] },
      { word: "a",        isVerb: false },
      { word: "letter",   isVerb: false },
      { word: "and",      isVerb: false },
      { word: "her",      isVerb: false },
      { word: "teacher",  isVerb: false },
      { word: "felt",     isVerb: true,  type: "Linking", choices: ["Linking", "Action", "Helping"] },
      { word: "proud",    isVerb: false },
      { word: ".",        isVerb: false },
    ],
  },
];

export default PARAGRAPHS;
