const PARAGRAPHS = [
  {
    id: 1,
    tokens: [
      { word: "She",       isAdv: false },
      { word: "sang",      isAdv: false },
      { word: "beautifully", isAdv: true, type: "Manner",    choices: ["Manner", "Time", "Place"] },
      { word: "at",        isAdv: false },
      { word: "the",       isAdv: false },
      { word: "concert",   isAdv: false },
      { word: "yesterday", isAdv: true,  type: "Time",       choices: ["Time", "Manner", "Frequency"] },
      { word: ".",         isAdv: false },
      { word: "Everyone",  isAdv: false },
      { word: "clapped",   isAdv: false },
      { word: "loudly",    isAdv: true,  type: "Manner",     choices: ["Manner", "Degree", "Place"] },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 2,
    tokens: [
      { word: "He",        isAdv: false },
      { word: "always",    isAdv: true,  type: "Frequency",  choices: ["Frequency", "Time", "Manner"] },
      { word: "wakes",     isAdv: false },
      { word: "up",        isAdv: false },
      { word: "early",     isAdv: true,  type: "Time",       choices: ["Time", "Frequency", "Degree"] },
      { word: "and",       isAdv: false },
      { word: "exercises", isAdv: false },
      { word: "outside",   isAdv: true,  type: "Place",      choices: ["Place", "Manner", "Time"] },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 3,
    tokens: [
      { word: "The",       isAdv: false },
      { word: "dog",       isAdv: false },
      { word: "barked",    isAdv: false },
      { word: "very",      isAdv: true,  type: "Degree",     choices: ["Degree", "Manner", "Frequency"] },
      { word: "loudly",    isAdv: true,  type: "Manner",     choices: ["Manner", "Place", "Time"] },
      { word: "upstairs",  isAdv: true,  type: "Place",      choices: ["Place", "Degree", "Manner"] },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 4,
    tokens: [
      { word: "We",        isAdv: false },
      { word: "sometimes", isAdv: true,  type: "Frequency",  choices: ["Frequency", "Manner", "Degree"] },
      { word: "go",        isAdv: false },
      { word: "there",     isAdv: true,  type: "Place",      choices: ["Place", "Time", "Manner"] },
      { word: "on",        isAdv: false },
      { word: "weekends",  isAdv: false },
      { word: ".",         isAdv: false },
      { word: "It",        isAdv: false },
      { word: "is",        isAdv: false },
      { word: "quite",     isAdv: true,  type: "Degree",     choices: ["Degree", "Frequency", "Place"] },
      { word: "far",       isAdv: true,  type: "Place",      choices: ["Place", "Manner", "Time"] },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 5,
    tokens: [
      { word: "She",       isAdv: false },
      { word: "quickly",   isAdv: true,  type: "Manner",     choices: ["Manner", "Time", "Degree"] },
      { word: "finished",  isAdv: false },
      { word: "her",       isAdv: false },
      { word: "homework",  isAdv: false },
      { word: "and",       isAdv: false },
      { word: "immediately", isAdv: true, type: "Time",      choices: ["Time", "Manner", "Frequency"] },
      { word: "went",      isAdv: false },
      { word: "outside",   isAdv: true,  type: "Place",      choices: ["Place", "Degree", "Manner"] },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 6,
    tokens: [
      { word: "The",       isAdv: false },
      { word: "rain",      isAdv: false },
      { word: "fell",      isAdv: false },
      { word: "steadily",  isAdv: true,  type: "Manner",     choices: ["Manner", "Degree", "Time"] },
      { word: "all",       isAdv: false },
      { word: "night",     isAdv: false },
      { word: ".",         isAdv: false },
      { word: "We",        isAdv: false },
      { word: "rarely",    isAdv: true,  type: "Frequency",  choices: ["Frequency", "Manner", "Place"] },
      { word: "see",       isAdv: false },
      { word: "such",      isAdv: false },
      { word: "heavy",     isAdv: false },
      { word: "storms",    isAdv: false },
      { word: "here",      isAdv: true,  type: "Place",      choices: ["Place", "Time", "Degree"] },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 7,
    tokens: [
      { word: "Jake",      isAdv: false },
      { word: "almost",    isAdv: true,  type: "Degree",     choices: ["Degree", "Manner", "Frequency"] },
      { word: "missed",    isAdv: false },
      { word: "the",       isAdv: false },
      { word: "bus",       isAdv: false },
      { word: "today",     isAdv: true,  type: "Time",       choices: ["Time", "Place", "Degree"] },
      { word: ".",         isAdv: false },
      { word: "He",        isAdv: false },
      { word: "ran",       isAdv: false },
      { word: "swiftly",   isAdv: true,  type: "Manner",     choices: ["Manner", "Frequency", "Place"] },
      { word: "down",      isAdv: true,  type: "Place",      choices: ["Place", "Time", "Degree"] },
      { word: "the",       isAdv: false },
      { word: "street",    isAdv: false },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 8,
    tokens: [
      { word: "The",       isAdv: false },
      { word: "teacher",   isAdv: false },
      { word: "spoke",     isAdv: false },
      { word: "clearly",   isAdv: true,  type: "Manner",     choices: ["Manner", "Time", "Degree"] },
      { word: "and",       isAdv: false },
      { word: "everyone",  isAdv: false },
      { word: "listened",  isAdv: false },
      { word: "quietly",   isAdv: true,  type: "Manner",     choices: ["Manner", "Frequency", "Place"] },
      { word: ".",         isAdv: false },
      { word: "The",       isAdv: false },
      { word: "lesson",    isAdv: false },
      { word: "was",       isAdv: false },
      { word: "extremely", isAdv: true,  type: "Degree",     choices: ["Degree", "Manner", "Time"] },
      { word: "interesting", isAdv: false },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 9,
    tokens: [
      { word: "Sam",       isAdv: false },
      { word: "never",     isAdv: true,  type: "Frequency",  choices: ["Frequency", "Time", "Manner"] },
      { word: "forgets",   isAdv: false },
      { word: "his",       isAdv: false },
      { word: "lunch",     isAdv: false },
      { word: ".",         isAdv: false },
      { word: "He",        isAdv: false },
      { word: "carefully", isAdv: true,  type: "Manner",     choices: ["Manner", "Degree", "Frequency"] },
      { word: "packs",     isAdv: false },
      { word: "his",       isAdv: false },
      { word: "bag",       isAdv: false },
      { word: "every",     isAdv: false },
      { word: "night",     isAdv: false },
      { word: ".",         isAdv: false },
    ],
  },
  {
    id: 10,
    tokens: [
      { word: "Emma",      isAdv: false },
      { word: "looked",    isAdv: false },
      { word: "everywhere", isAdv: true, type: "Place",      choices: ["Place", "Manner", "Frequency"] },
      { word: "for",       isAdv: false },
      { word: "her",       isAdv: false },
      { word: "keys",      isAdv: false },
      { word: ".",         isAdv: false },
      { word: "She",       isAdv: false },
      { word: "finally",   isAdv: true,  type: "Time",       choices: ["Time", "Degree", "Manner"] },
      { word: "found",     isAdv: false },
      { word: "them",      isAdv: false },
      { word: "inside",    isAdv: true,  type: "Place",      choices: ["Place", "Time", "Frequency"] },
      { word: "her",       isAdv: false },
      { word: "backpack",  isAdv: false },
      { word: ".",         isAdv: false },
    ],
  },
];

export default PARAGRAPHS;
