const PARAGRAPHS = [
  {
    id: 1,
    tokens: [
      { word: "I",           isConj: false },
      { word: "wanted",      isConj: false },
      { word: "to",          isConj: false },
      { word: "go",          isConj: false },
      { word: "outside",     isConj: false },
      { word: "but",         isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "it",          isConj: false },
      { word: "was",         isConj: false },
      { word: "raining",     isConj: false },
      { word: ".",           isConj: false },
      { word: "So",          isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "I",           isConj: false },
      { word: "stayed",      isConj: false },
      { word: "home",        isConj: false },
      { word: "and",         isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "read",        isConj: false },
      { word: "a",           isConj: false },
      { word: "book",        isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 2,
    tokens: [
      { word: "We",          isConj: false },
      { word: "stayed",      isConj: false },
      { word: "inside",      isConj: false },
      { word: "because",     isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "it",          isConj: false },
      { word: "was",         isConj: false },
      { word: "very",        isConj: false },
      { word: "cold",        isConj: false },
      { word: ".",           isConj: false },
      { word: "Although",    isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "we",          isConj: false },
      { word: "were",        isConj: false },
      { word: "bored",       isConj: false },
      { word: ",",           isConj: false },
      { word: "we",          isConj: false },
      { word: "had",         isConj: false },
      { word: "fun",         isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 3,
    tokens: [
      { word: "Both",        isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "Jake",        isConj: false },
      { word: "and",         isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "Emma",        isConj: false },
      { word: "love",        isConj: false },
      { word: "soccer",      isConj: false },
      { word: ".",           isConj: false },
      { word: "They",        isConj: false },
      { word: "practice",    isConj: false },
      { word: "whenever",    isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "they",        isConj: false },
      { word: "can",         isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 4,
    tokens: [
      { word: "She",         isConj: false },
      { word: "studied",     isConj: false },
      { word: "hard",        isConj: false },
      { word: "so",          isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "she",         isConj: false },
      { word: "passed",      isConj: false },
      { word: "the",         isConj: false },
      { word: "test",        isConj: false },
      { word: ".",           isConj: false },
      { word: "If",          isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "you",         isConj: false },
      { word: "study",       isConj: false },
      { word: "too",         isConj: false },
      { word: ",",           isConj: false },
      { word: "you",         isConj: false },
      { word: "will",        isConj: false },
      { word: "do",          isConj: false },
      { word: "well",        isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 5,
    tokens: [
      { word: "Neither",     isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "Sam",         isConj: false },
      { word: "nor",         isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "his",         isConj: false },
      { word: "sister",      isConj: false },
      { word: "wanted",      isConj: false },
      { word: "to",          isConj: false },
      { word: "clean",       isConj: false },
      { word: "the",         isConj: false },
      { word: "room",        isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 6,
    tokens: [
      { word: "I",           isConj: false },
      { word: "will",        isConj: false },
      { word: "help",        isConj: false },
      { word: "you",         isConj: false },
      { word: "unless",      isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "you",         isConj: false },
      { word: "are",         isConj: false },
      { word: "rude",        isConj: false },
      { word: ".",           isConj: false },
      { word: "You",         isConj: false },
      { word: "can",         isConj: false },
      { word: "either",      isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "ask",         isConj: false },
      { word: "nicely",      isConj: false },
      { word: "or",          isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "do",          isConj: false },
      { word: "it",          isConj: false },
      { word: "yourself",    isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 7,
    tokens: [
      { word: "We",          isConj: false },
      { word: "waited",      isConj: false },
      { word: "until",       isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "the",         isConj: false },
      { word: "rain",        isConj: false },
      { word: "stopped",     isConj: false },
      { word: "and",         isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "then",        isConj: false },
      { word: "went",        isConj: false },
      { word: "outside",     isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 8,
    tokens: [
      { word: "Not",         isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "only",        isConj: false },
      { word: "did",         isConj: false },
      { word: "she",         isConj: false },
      { word: "win",         isConj: false },
      { word: "the",         isConj: false },
      { word: "race",        isConj: false },
      { word: ",",           isConj: false },
      { word: "but",         isConj: true,  type: "Correlative",   choices: ["Correlative", "Coordinating", "Subordinating"] },
      { word: "she",         isConj: false },
      { word: "also",        isConj: false },
      { word: "set",         isConj: false },
      { word: "a",           isConj: false },
      { word: "record",      isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 9,
    tokens: [
      { word: "He",          isConj: false },
      { word: "was",         isConj: false },
      { word: "tired",       isConj: false },
      { word: "yet",         isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "he",          isConj: false },
      { word: "kept",        isConj: false },
      { word: "working",     isConj: false },
      { word: ".",           isConj: false },
      { word: "While",       isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "others",      isConj: false },
      { word: "rested",      isConj: false },
      { word: ",",           isConj: false },
      { word: "he",          isConj: false },
      { word: "finished",    isConj: false },
      { word: "the",         isConj: false },
      { word: "job",         isConj: false },
      { word: ".",           isConj: false },
    ],
  },
  {
    id: 10,
    tokens: [
      { word: "I",           isConj: false },
      { word: "like",        isConj: false },
      { word: "cats",        isConj: false },
      { word: "and",         isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "dogs",        isConj: false },
      { word: ",",           isConj: false },
      { word: "but",         isConj: true,  type: "Coordinating",  choices: ["Coordinating", "Subordinating", "Correlative"] },
      { word: "my",          isConj: false },
      { word: "brother",     isConj: false },
      { word: "prefers",     isConj: false },
      { word: "fish",        isConj: false },
      { word: "since",       isConj: true,  type: "Subordinating", choices: ["Subordinating", "Coordinating", "Correlative"] },
      { word: "they",        isConj: false },
      { word: "are",         isConj: false },
      { word: "quiet",       isConj: false },
      { word: ".",           isConj: false },
    ],
  },
];

export default PARAGRAPHS;
