const PARAGRAPHS = [
  {
    id: 1,
    tokens: [
      { word: "The",      isPrep: false },
      { word: "cat",      isPrep: false },
      { word: "sat",      isPrep: false },
      { word: "on",       isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "mat",      isPrep: false },
      { word: "near",     isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "door",     isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 2,
    tokens: [
      { word: "She",      isPrep: false },
      { word: "walked",   isPrep: false },
      { word: "across",   isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "bridge",   isPrep: false },
      { word: "and",      isPrep: false },
      { word: "sat",      isPrep: false },
      { word: "next",     isPrep: true,  type: "Compound",   choices: ["Compound", "Simple", "Phrase"] },
      { word: "to",       isPrep: false },
      { word: "her",      isPrep: false },
      { word: "friend",   isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 3,
    tokens: [
      { word: "The",      isPrep: false },
      { word: "book",     isPrep: false },
      { word: "is",       isPrep: false },
      { word: "on",       isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "top",      isPrep: false },
      { word: "of",       isPrep: false },
      { word: "the",      isPrep: false },
      { word: "shelf",    isPrep: false },
      { word: ".",        isPrep: false },
      { word: "Look",     isPrep: false },
      { word: "inside",   isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "box",      isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 4,
    tokens: [
      { word: "We",       isPrep: false },
      { word: "traveled", isPrep: false },
      { word: "by",       isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "bus",      isPrep: false },
      { word: "because",  isPrep: false },
      { word: "of",       isPrep: false },
      { word: "the",      isPrep: false },
      { word: "rain",     isPrep: false },
      { word: ".",        isPrep: false },
      { word: "We",       isPrep: false },
      { word: "arrived",  isPrep: false },
      { word: "in",       isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "morning",  isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 5,
    tokens: [
      { word: "He",       isPrep: false },
      { word: "hid",      isPrep: false },
      { word: "behind",   isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "tree",     isPrep: false },
      { word: "and",      isPrep: false },
      { word: "jumped",   isPrep: false },
      { word: "over",     isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "fence",    isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 6,
    tokens: [
      { word: "She",      isPrep: false },
      { word: "waited",   isPrep: false },
      { word: "in",       isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "front",    isPrep: false },
      { word: "of",       isPrep: false },
      { word: "the",      isPrep: false },
      { word: "school",   isPrep: false },
      { word: "for",      isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "ten",      isPrep: false },
      { word: "minutes",  isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 7,
    tokens: [
      { word: "The",      isPrep: false },
      { word: "keys",     isPrep: false },
      { word: "are",      isPrep: false },
      { word: "under",    isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "table",    isPrep: false },
      { word: ".",        isPrep: false },
      { word: "Please",   isPrep: false },
      { word: "look",     isPrep: false },
      { word: "between",  isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "chairs",   isPrep: false },
      { word: "too",      isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 8,
    tokens: [
      { word: "Jake",     isPrep: false },
      { word: "sat",      isPrep: false },
      { word: "next",     isPrep: true,  type: "Compound",   choices: ["Compound", "Simple", "Phrase"] },
      { word: "to",       isPrep: false },
      { word: "his",      isPrep: false },
      { word: "best",     isPrep: false },
      { word: "friend",   isPrep: false },
      { word: "at",       isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "lunch",    isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 9,
    tokens: [
      { word: "The",      isPrep: false },
      { word: "dog",      isPrep: false },
      { word: "ran",      isPrep: false },
      { word: "through",  isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "garden",   isPrep: false },
      { word: "and",      isPrep: false },
      { word: "jumped",   isPrep: false },
      { word: "into",     isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "pond",     isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
  {
    id: 10,
    tokens: [
      { word: "She",      isPrep: false },
      { word: "walked",   isPrep: false },
      { word: "along",    isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "the",      isPrep: false },
      { word: "river",    isPrep: false },
      { word: "and",      isPrep: false },
      { word: "sat",      isPrep: false },
      { word: "on",       isPrep: true,  type: "Simple",     choices: ["Simple", "Compound", "Phrase"] },
      { word: "top",      isPrep: false },
      { word: "of",       isPrep: false },
      { word: "a",        isPrep: false },
      { word: "big",      isPrep: false },
      { word: "rock",     isPrep: false },
      { word: ".",        isPrep: false },
    ],
  },
];

export default PARAGRAPHS;
