const PARAGRAPHS = [
  {
    id: 1,
    tokens: [
      { word: "The",       isAdj: false },
      { word: "little",    isAdj: true,  type: "Descriptive", choices: ["Descriptive", "Comparative", "Possessive"] },
      { word: "brown",     isAdj: true,  type: "Descriptive", choices: ["Descriptive", "Proper", "Quantitative"] },
      { word: "dog",       isAdj: false },
      { word: "ran",       isAdj: false },
      { word: "across",    isAdj: false },
      { word: "the",       isAdj: false },
      { word: "muddy",     isAdj: true,  type: "Descriptive", choices: ["Descriptive", "Demonstrative", "Comparative"] },
      { word: "field",     isAdj: false },
      { word: ".",         isAdj: false },
      { word: "It",        isAdj: false },
      { word: "was",       isAdj: false },
      { word: "a",         isAdj: false },
      { word: "sunny",     isAdj: true,  type: "Descriptive", choices: ["Descriptive", "Quantitative", "Proper"] },
      { word: "day",       isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 2,
    tokens: [
      { word: "My",        isAdj: false },
      { word: "older",     isAdj: true,  type: "Comparative", choices: ["Comparative", "Descriptive", "Possessive"] },
      { word: "sister",    isAdj: false },
      { word: "has",       isAdj: false },
      { word: "a",         isAdj: false },
      { word: "faster",    isAdj: true,  type: "Comparative", choices: ["Comparative", "Descriptive", "Quantitative"] },
      { word: "bike",      isAdj: false },
      { word: "than",      isAdj: false },
      { word: "mine",      isAdj: false },
      { word: ".",         isAdj: false },
      { word: "She",       isAdj: false },
      { word: "is",        isAdj: false },
      { word: "also",      isAdj: false },
      { word: "taller",    isAdj: true,  type: "Comparative", choices: ["Comparative", "Superlative", "Descriptive"] },
      { word: "and",       isAdj: false },
      { word: "stronger",  isAdj: true,  type: "Comparative", choices: ["Comparative", "Superlative", "Proper"] },
      { word: "than",      isAdj: false },
      { word: "me",        isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 3,
    tokens: [
      { word: "This",      isAdj: true,  type: "Demonstrative", choices: ["Demonstrative", "Descriptive", "Quantitative"] },
      { word: "red",       isAdj: true,  type: "Descriptive",   choices: ["Descriptive", "Proper", "Comparative"] },
      { word: "backpack",  isAdj: false },
      { word: "belongs",   isAdj: false },
      { word: "to",        isAdj: false },
      { word: "that",      isAdj: true,  type: "Demonstrative", choices: ["Demonstrative", "Possessive", "Descriptive"] },
      { word: "new",       isAdj: true,  type: "Descriptive",   choices: ["Descriptive", "Comparative", "Quantitative"] },
      { word: "student",   isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 4,
    tokens: [
      { word: "We",        isAdj: false },
      { word: "ate",       isAdj: false },
      { word: "three",     isAdj: true,  type: "Quantitative", choices: ["Quantitative", "Descriptive", "Demonstrative"] },
      { word: "warm",      isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Comparative", "Proper"] },
      { word: "slices",    isAdj: false },
      { word: "of",        isAdj: false },
      { word: "pizza",     isAdj: false },
      { word: "after",     isAdj: false },
      { word: "the",       isAdj: false },
      { word: "long",      isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Quantitative", "Comparative"] },
      { word: "game",      isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 5,
    tokens: [
      { word: "The",       isAdj: false },
      { word: "best",      isAdj: true,  type: "Superlative",  choices: ["Superlative", "Comparative", "Descriptive"] },
      { word: "part",      isAdj: false },
      { word: "of",        isAdj: false },
      { word: "summer",    isAdj: false },
      { word: "is",        isAdj: false },
      { word: "the",       isAdj: false },
      { word: "cool",      isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Comparative", "Quantitative"] },
      { word: "breeze",    isAdj: false },
      { word: "on",        isAdj: false },
      { word: "a",         isAdj: false },
      { word: "hot",       isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Superlative", "Proper"] },
      { word: "day",       isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 6,
    tokens: [
      { word: "She",       isAdj: false },
      { word: "wore",      isAdj: false },
      { word: "a",         isAdj: false },
      { word: "beautiful", isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Proper", "Comparative"] },
      { word: "blue",      isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Demonstrative", "Quantitative"] },
      { word: "dress",     isAdj: false },
      { word: "to",        isAdj: false },
      { word: "the",       isAdj: false },
      { word: "American",  isAdj: true,  type: "Proper",       choices: ["Proper", "Descriptive", "Demonstrative"] },
      { word: "festival",  isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 7,
    tokens: [
      { word: "These",     isAdj: true,  type: "Demonstrative", choices: ["Demonstrative", "Quantitative", "Descriptive"] },
      { word: "five",      isAdj: true,  type: "Quantitative",  choices: ["Quantitative", "Descriptive", "Demonstrative"] },
      { word: "fluffy",    isAdj: true,  type: "Descriptive",   choices: ["Descriptive", "Comparative", "Proper"] },
      { word: "kittens",   isAdj: false },
      { word: "need",      isAdj: false },
      { word: "a",         isAdj: false },
      { word: "warm",      isAdj: true,  type: "Descriptive",   choices: ["Descriptive", "Superlative", "Quantitative"] },
      { word: "home",      isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 8,
    tokens: [
      { word: "The",       isAdj: false },
      { word: "tallest",   isAdj: true,  type: "Superlative",  choices: ["Superlative", "Comparative", "Descriptive"] },
      { word: "building",  isAdj: false },
      { word: "in",        isAdj: false },
      { word: "the",       isAdj: false },
      { word: "city",      isAdj: false },
      { word: "has",       isAdj: false },
      { word: "many",      isAdj: true,  type: "Quantitative",  choices: ["Quantitative", "Descriptive", "Demonstrative"] },
      { word: "glass",     isAdj: true,  type: "Descriptive",   choices: ["Descriptive", "Proper", "Comparative"] },
      { word: "windows",   isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 9,
    tokens: [
      { word: "Jake",      isAdj: false },
      { word: "found",     isAdj: false },
      { word: "an",        isAdj: false },
      { word: "old",       isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Comparative", "Quantitative"] },
      { word: "wooden",    isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Proper", "Demonstrative"] },
      { word: "box",       isAdj: false },
      { word: "under",     isAdj: false },
      { word: "his",       isAdj: false },
      { word: "dusty",     isAdj: true,  type: "Descriptive",  choices: ["Descriptive", "Superlative", "Quantitative"] },
      { word: "bed",       isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
  {
    id: 10,
    tokens: [
      { word: "The",       isAdj: false },
      { word: "Mexican",   isAdj: true,  type: "Proper",       choices: ["Proper", "Descriptive", "Demonstrative"] },
      { word: "food",      isAdj: false },
      { word: "at",        isAdj: false },
      { word: "that",      isAdj: true,  type: "Demonstrative", choices: ["Demonstrative", "Descriptive", "Quantitative"] },
      { word: "small",     isAdj: true,  type: "Descriptive",   choices: ["Descriptive", "Comparative", "Proper"] },
      { word: "restaurant",isAdj: false },
      { word: "was",       isAdj: false },
      { word: "the",       isAdj: false },
      { word: "spiciest",  isAdj: true,  type: "Superlative",   choices: ["Superlative", "Comparative", "Descriptive"] },
      { word: "I",         isAdj: false },
      { word: "have",      isAdj: false },
      { word: "ever",      isAdj: false },
      { word: "tried",     isAdj: false },
      { word: ".",         isAdj: false },
    ],
  },
];

export default PARAGRAPHS;
