const PARAGRAPHS = [
  {
    id: 1,
    tokens: [
      { word: "I",         isArticle: false },
      { word: "saw",       isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "dog",       isArticle: false },
      { word: "in",        isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "park",      isArticle: false },
      { word: ".",         isArticle: false },
      { word: "The",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "dog",       isArticle: false },
      { word: "was",       isArticle: false },
      { word: "chasing",   isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "ball",      isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 2,
    tokens: [
      { word: "She",       isArticle: false },
      { word: "is",        isArticle: false },
      { word: "an",        isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "excellent", isArticle: false },
      { word: "student",   isArticle: false },
      { word: ".",         isArticle: false },
      { word: "She",       isArticle: false },
      { word: "loves",     isArticle: false },
      { word: "music",     isArticle: false },
      { word: "and",       isArticle: false },
      { word: "plays",     isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "piano",     isArticle: false },
      { word: "every",     isArticle: false },
      { word: "day",       isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 3,
    tokens: [
      { word: "We",        isArticle: false },
      { word: "went",      isArticle: false },
      { word: "to",        isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "beach",     isArticle: false },
      { word: "and",       isArticle: false },
      { word: "built",     isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "sandcastle",isArticle: false },
      { word: ".",         isArticle: false },
      { word: "The",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "waves",     isArticle: false },
      { word: "knocked",   isArticle: false },
      { word: "it",        isArticle: false },
      { word: "down",      isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 4,
    tokens: [
      { word: "Jake",      isArticle: false },
      { word: "wants",     isArticle: false },
      { word: "to",        isArticle: false },
      { word: "be",        isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "doctor",    isArticle: false },
      { word: "when",      isArticle: false },
      { word: "he",        isArticle: false },
      { word: "grows",     isArticle: false },
      { word: "up",        isArticle: false },
      { word: ".",         isArticle: false },
      { word: "He",        isArticle: false },
      { word: "loves",     isArticle: false },
      { word: "science",   isArticle: false },
      { word: "and",       isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "human",     isArticle: false },
      { word: "body",      isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 5,
    tokens: [
      { word: "I",         isArticle: false },
      { word: "have",      isArticle: false },
      { word: "an",        isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "idea",      isArticle: false },
      { word: "for",       isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "project",   isArticle: false },
      { word: ".",         isArticle: false },
      { word: "We",        isArticle: false },
      { word: "should",    isArticle: false },
      { word: "use",       isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "computer",  isArticle: false },
      { word: "in",        isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "library",   isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 6,
    tokens: [
      { word: "The",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "sun",       isArticle: false },
      { word: "rises",     isArticle: false },
      { word: "in",        isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "east",      isArticle: false },
      { word: ".",         isArticle: false },
      { word: "It",        isArticle: false },
      { word: "gives",     isArticle: false },
      { word: "us",        isArticle: false },
      { word: "light",     isArticle: false },
      { word: "and",       isArticle: false },
      { word: "warmth",    isArticle: false },
      { word: "every",     isArticle: false },
      { word: "morning",   isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 7,
    tokens: [
      { word: "Emma",      isArticle: false },
      { word: "found",     isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "lost",      isArticle: false },
      { word: "kitten",    isArticle: false },
      { word: "near",      isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "school",    isArticle: false },
      { word: ".",         isArticle: false },
      { word: "She",       isArticle: false },
      { word: "gave",      isArticle: false },
      { word: "it",        isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "warm",      isArticle: false },
      { word: "home",      isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 8,
    tokens: [
      { word: "I",         isArticle: false },
      { word: "need",      isArticle: false },
      { word: "an",        isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "umbrella",  isArticle: false },
      { word: "because",   isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "sky",       isArticle: false },
      { word: "looks",     isArticle: false },
      { word: "cloudy",    isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 9,
    tokens: [
      { word: "Sam",       isArticle: false },
      { word: "bought",    isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "new",       isArticle: false },
      { word: "book",      isArticle: false },
      { word: "from",      isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "store",     isArticle: false },
      { word: ".",         isArticle: false },
      { word: "The",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "book",      isArticle: false },
      { word: "was",       isArticle: false },
      { word: "about",     isArticle: false },
      { word: "animals",   isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
  {
    id: 10,
    tokens: [
      { word: "There",     isArticle: false },
      { word: "is",        isArticle: false },
      { word: "a",         isArticle: true,  type: "Indefinite", choices: ["Indefinite", "Definite", "Zero Article"] },
      { word: "beautiful", isArticle: false },
      { word: "garden",    isArticle: false },
      { word: "behind",    isArticle: false },
      { word: "the",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "school",    isArticle: false },
      { word: ".",         isArticle: false },
      { word: "The",       isArticle: true,  type: "Definite",   choices: ["Definite", "Indefinite", "Zero Article"] },
      { word: "flowers",   isArticle: false },
      { word: "bloom",     isArticle: false },
      { word: "every",     isArticle: false },
      { word: "spring",    isArticle: false },
      { word: ".",         isArticle: false },
    ],
  },
];

export default PARAGRAPHS;
