const PARAGRAPHS = [
  {
    id: 1,
    tokens: [
      { word: "My",        isNoun: false },
      { word: "dog",       isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Abstract"] },
      { word: "loves",     isNoun: false },
      { word: "to",        isNoun: false },
      { word: "play",      isNoun: false },
      { word: "in",        isNoun: false },
      { word: "the",       isNoun: false },
      { word: "park",      isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Proper"] },
      { word: ".",         isNoun: false },
      { word: "He",        isNoun: false },
      { word: "chases",    isNoun: false },
      { word: "every",     isNoun: false },
      { word: "ball",      isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Common"] },
      { word: "with",      isNoun: false },
      { word: "so",        isNoun: false },
      { word: "much",      isNoun: false },
      { word: "joy",       isNoun: true,  type: "Abstract",    choices: ["Abstract", "Concrete", "Proper"] },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 2,
    tokens: [
      { word: "Our",       isNoun: false },
      { word: "class",     isNoun: true,  type: "Collective",  choices: ["Collective", "Common", "Abstract"] },
      { word: "went",      isNoun: false },
      { word: "on",        isNoun: false },
      { word: "a",         isNoun: false },
      { word: "trip",      isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Concrete"] },
      { word: "to",        isNoun: false },
      { word: "the",       isNoun: false },
      { word: "zoo",       isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Proper"] },
      { word: ".",         isNoun: false },
      { word: "We",        isNoun: false },
      { word: "saw",       isNoun: false },
      { word: "a",         isNoun: false },
      { word: "group",     isNoun: true,  type: "Collective",  choices: ["Collective", "Common", "Countable"] },
      { word: "of",        isNoun: false },
      { word: "monkeys",   isNoun: true,  type: "Countable",   choices: ["Countable", "Uncountable", "Proper"] },
      { word: "playing",   isNoun: false },
      { word: "together",  isNoun: false },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 3,
    tokens: [
      { word: "Emma",      isNoun: true,  type: "Proper",      choices: ["Proper", "Common", "Abstract"] },
      { word: "packed",    isNoun: false },
      { word: "her",       isNoun: false },
      { word: "backpack",  isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Common"] },
      { word: "with",      isNoun: false },
      { word: "books",     isNoun: true,  type: "Countable",   choices: ["Countable", "Uncountable", "Concrete"] },
      { word: "and",       isNoun: false },
      { word: "a",         isNoun: false },
      { word: "sandwich",  isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Countable"] },
      { word: ".",         isNoun: false },
      { word: "She",       isNoun: false },
      { word: "felt",      isNoun: false },
      { word: "a",         isNoun: false },
      { word: "wave",      isNoun: true,  type: "Abstract",    choices: ["Abstract", "Concrete", "Common"] },
      { word: "of",        isNoun: false },
      { word: "excitement",isNoun: true,  type: "Abstract",    choices: ["Abstract", "Concrete", "Uncountable"] },
      { word: "for",       isNoun: false },
      { word: "her",       isNoun: false },
      { word: "first",     isNoun: false },
      { word: "day",       isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Countable"] },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 4,
    tokens: [
      { word: "The",       isNoun: false },
      { word: "team",      isNoun: true,  type: "Collective",  choices: ["Collective", "Common", "Abstract"] },
      { word: "won",       isNoun: false },
      { word: "the",       isNoun: false },
      { word: "game",      isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Concrete"] },
      { word: "and",       isNoun: false },
      { word: "the",       isNoun: false },
      { word: "coach",     isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Collective"] },
      { word: "gave",      isNoun: false },
      { word: "everyone",  isNoun: false },
      { word: "a",         isNoun: false },
      { word: "trophy",    isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Countable"] },
      { word: ".",         isNoun: false },
      { word: "The",       isNoun: false },
      { word: "pride",     isNoun: true,  type: "Abstract",    choices: ["Abstract", "Concrete", "Common"] },
      { word: "on",        isNoun: false },
      { word: "their",     isNoun: false },
      { word: "faces",     isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Countable"] },
      { word: "said",      isNoun: false },
      { word: "it",        isNoun: false },
      { word: "all",       isNoun: false },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 5,
    tokens: [
      { word: "Jake",      isNoun: true,  type: "Proper",      choices: ["Proper", "Common", "Collective"] },
      { word: "left",      isNoun: false },
      { word: "his",       isNoun: false },
      { word: "shoes",     isNoun: true,  type: "Countable",   choices: ["Countable", "Uncountable", "Concrete"] },
      { word: "by",        isNoun: false },
      { word: "the",       isNoun: false },
      { word: "door",      isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Common"] },
      { word: "and",       isNoun: false },
      { word: "ran",       isNoun: false },
      { word: "into",      isNoun: false },
      { word: "the",       isNoun: false },
      { word: "kitchen",   isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Proper"] },
      { word: ".",         isNoun: false },
      { word: "The",       isNoun: false },
      { word: "smell",     isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Common"] },
      { word: "of",        isNoun: false },
      { word: "cookies",   isNoun: true,  type: "Countable",   choices: ["Countable", "Uncountable", "Proper"] },
      { word: "filled",    isNoun: false },
      { word: "the",       isNoun: false },
      { word: "room",      isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Collective"] },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 6,
    tokens: [
      { word: "A",         isNoun: false },
      { word: "flock",     isNoun: true,  type: "Collective",  choices: ["Collective", "Common", "Abstract"] },
      { word: "of",        isNoun: false },
      { word: "birds",     isNoun: true,  type: "Countable",   choices: ["Countable", "Uncountable", "Concrete"] },
      { word: "flew",      isNoun: false },
      { word: "over",      isNoun: false },
      { word: "our",       isNoun: false },
      { word: "school",    isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Proper"] },
      { word: ".",         isNoun: false },
      { word: "We",        isNoun: false },
      { word: "stopped",   isNoun: false },
      { word: "and",       isNoun: false },
      { word: "watched",   isNoun: false },
      { word: "them",      isNoun: false },
      { word: "with",      isNoun: false },
      { word: "wonder",    isNoun: true,  type: "Abstract",    choices: ["Abstract", "Concrete", "Uncountable"] },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 7,
    tokens: [
      { word: "The",       isNoun: false },
      { word: "library",   isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Proper"] },
      { word: "was",       isNoun: false },
      { word: "full",      isNoun: false },
      { word: "of",        isNoun: false },
      { word: "children",  isNoun: true,  type: "Common",      choices: ["Common", "Collective", "Proper"] },
      { word: "reading",   isNoun: false },
      { word: "books",     isNoun: true,  type: "Countable",   choices: ["Countable", "Uncountable", "Abstract"] },
      { word: "about",     isNoun: false },
      { word: "science",   isNoun: true,  type: "Uncountable", choices: ["Uncountable", "Countable", "Abstract"] },
      { word: "and",       isNoun: false },
      { word: "nature",    isNoun: true,  type: "Uncountable", choices: ["Uncountable", "Abstract", "Concrete"] },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 8,
    tokens: [
      { word: "On",        isNoun: false },
      { word: "Monday",    isNoun: true,  type: "Proper",      choices: ["Proper", "Common", "Abstract"] },
      { word: ",",         isNoun: false },
      { word: "our",       isNoun: false },
      { word: "teacher",   isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Collective"] },
      { word: "brought",   isNoun: false },
      { word: "a",         isNoun: false },
      { word: "basket",    isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Countable"] },
      { word: "of",        isNoun: false },
      { word: "fruit",     isNoun: true,  type: "Uncountable", choices: ["Uncountable", "Countable", "Concrete"] },
      { word: "to",        isNoun: false },
      { word: "share",     isNoun: false },
      { word: "with",      isNoun: false },
      { word: "the",       isNoun: false },
      { word: "class",     isNoun: true,  type: "Collective",  choices: ["Collective", "Common", "Proper"] },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 9,
    tokens: [
      { word: "Sam",       isNoun: true,  type: "Proper",      choices: ["Proper", "Common", "Collective"] },
      { word: "drew",      isNoun: false },
      { word: "a",         isNoun: false },
      { word: "picture",   isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Countable"] },
      { word: "of",        isNoun: false },
      { word: "his",       isNoun: false },
      { word: "family",    isNoun: true,  type: "Collective",  choices: ["Collective", "Common", "Abstract"] },
      { word: "using",     isNoun: false },
      { word: "crayons",   isNoun: true,  type: "Countable",   choices: ["Countable", "Uncountable", "Concrete"] },
      { word: ".",         isNoun: false },
      { word: "His",       isNoun: false },
      { word: "mom",       isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Concrete"] },
      { word: "hung",      isNoun: false },
      { word: "it",        isNoun: false },
      { word: "on",        isNoun: false },
      { word: "the",       isNoun: false },
      { word: "wall",      isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Proper"] },
      { word: "with",      isNoun: false },
      { word: "pride",     isNoun: true,  type: "Abstract",    choices: ["Abstract", "Concrete", "Uncountable"] },
      { word: ".",         isNoun: false },
    ],
  },
  {
    id: 10,
    tokens: [
      { word: "The",       isNoun: false },
      { word: "children",  isNoun: true,  type: "Common",      choices: ["Common", "Collective", "Proper"] },
      { word: "built",     isNoun: false },
      { word: "a",         isNoun: false },
      { word: "sandcastle",isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Countable"] },
      { word: "near",      isNoun: false },
      { word: "the",       isNoun: false },
      { word: "water",     isNoun: true,  type: "Uncountable", choices: ["Uncountable", "Countable", "Abstract"] },
      { word: ".",         isNoun: false },
      { word: "Their",     isNoun: false },
      { word: "laughter",  isNoun: true,  type: "Abstract",    choices: ["Abstract", "Concrete", "Uncountable"] },
      { word: "echoed",    isNoun: false },
      { word: "across",    isNoun: false },
      { word: "the",       isNoun: false },
      { word: "beach",     isNoun: true,  type: "Concrete",    choices: ["Concrete", "Abstract", "Proper"] },
      { word: "all",       isNoun: false },
      { word: "afternoon", isNoun: true,  type: "Common",      choices: ["Common", "Proper", "Abstract"] },
      { word: ".",         isNoun: false },
    ],
  },
];

export default PARAGRAPHS;
